# Working with Pytorch tensors

Pytorch is build on tensors.
A Pytorch tensor is an n-dimensional array, similar to Numpy arrays
If you are familiar with Numpy, you will see a similarity in the syntax(구문) when working with tensors, as shown in the following table:

|NumPy Arrays|Pytorch tensors|Description|
|-----------|-------------|----------|
|numpy.ones(.)|torch.ones(.)|Create an array of ones|
|numpy.zeros(.)|torch.zeros(.)|Create an array of zeros|
|numpy.random.rand(.)|torch.rand(.)|Create a random array|
|numpy.array(.)|torch.tensor(.)|Create an array from given values|
|x.shape|x.shape or x.size()|Get an array shape|


In this table,<br>
1. define and change tensors<br>
2. convert(변하다) tensors into arrays<br>
3. move them between computing devices<br>

# How to do it ...

folliwing code example, launch Python or Jupyter Notebook

# Defining the tensor data type

The default tensor data type is **torch.float32**. This is the most used data type for tensor operations(조작,운영).

In [1]:
#1. Define a tensor with a default data type:
import torch
x = torch.ones(2,2)
print(x)
print(x.dtype) # 자료형

tensor([[1., 1.],
        [1., 1.]])
torch.float32


In [2]:
#2. Specify the data type when defining a tensor:
x = torch.ones(2,2,dtype=torch.int8)
print(x)
print(x.dtype)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)
torch.int8


# Changing the tensor's data type

We can change a tensor's data type using the ".type" method

In [3]:
#1. Define a tensor with torch.uint8 type:
x = torch.ones(1, dtype=torch.uint8)
print(x.dtype)

torch.uint8


In [4]:
#2. Change the tensor data type:
x = x.type(torch.float)
print(x.dtype)

torch.float32


# Converting tensor into Numpy arrays

convert PyTorch tensors into NumPy arrays

In [5]:
#1. Define a tensor:
x = torch.rand(2,2)
print(x)
print(x.dtype)

tensor([[0.7159, 0.1800],
        [0.1474, 0.5847]])
torch.float32


In [6]:
#2. Convert the tensor into a NumPy array:
y = x.numpy()
print(y)
print(y.dtype)

[[0.715915   0.18002516]
 [0.14739436 0.5846806 ]]
float32


# Converting Numpy arrays into tensors

convert NumPy arrays into  PyTorch tensors  

In [7]:
#1. Define a NumPy array:
import numpy as np
x = np.zeros((2,2),dtype=np.float32)
print(x)
print(x.dtype)

[[0. 0.]
 [0. 0.]]
float32


In [8]:
#2. Convert the NumPy array into a Pytorch tensor:
y = torch.from_numpy(x)
print(y)
print(y.dtype)

tensor([[0., 0.],
        [0., 0.]])
torch.float32


# Moving tensors between devices



Pytorch tensors are sorted on the CPU. Pytorch tensors can be utilized(활용) on a GPU to speed up coming. This is the main advantage(이점) of tensors compared(비교) to Numpy arrays. To get this advantage, we need to move the tensors to the CUDA(gpu 개발 tool) device. We can move tensors onto any device using the ".to" metohd

In [9]:
import torch
#1. Define a tensor on CPU:
x = torch.tensor([1.5,2])
print(x)
print(x.device)

tensor([1.5000, 2.0000])
cpu


In [16]:
#2. Define a CUDA device:
if torch.cuda.is_available():
    device = torch.device("cuda")


In [11]:
#3. Move the tensor onto the CUDA device:
x = x.to(device)
print(x)
print(x.device)

tensor([1.5000, 2.0000], device='cuda:0')
cuda:0


In [12]:
#4. Similarly, we can move tensors to CPU:
device = torch.device("cpu")
x = x.to(device)
print(x)
print(x.device)

tensor([1.5000, 2.0000])
cpu


In [15]:
#5. We can also directly create a tensor on any device:
device = torch.device("cuda:0")
x = torch.ones(2,2,device=device)
print(x)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')


# How it works...

First, we defined a tensor obtained(획득) the tensor type, and changed its type. Then, we converted(변환) PyTorch tensors into NumPy arrays and vice versa(그 반대). We also moved tensors between the CPU and CUDA devices. **Next, we showed you how to change a tensor data type using the ".type" method.** Then, we showed how to convert PyTorch tensors into Numpy arrays using the ".numpy method.

After that, we showed you how to convert a NumPy array into a Pytorch tensor using the ".from_numpy(x)" method. Then, to move tensors from a CPU device to a GPU device and vice versa, using the ".to"method. As you have seen,(보다시피) if you do not specifiy the device, the tensor will be hostrd on the CPU device.

Tensor types : https://pytorch.org.docs/stable/tensors.html

# 2021.03.06

# Loading and processing data

In most cases, it's assumed that we receive data in three groups : training, validation, test

We use the training dataset to train the model.
The validation dataset is used to track the model's performance during training.
We use the test dataset for the final evaluation of the model.
The target values of the test dataset are usually hidden from us.(테스트 데이터셋의 타겟값은 우리에게 숨겨져 있다.) We need at least one training dataset and one validation dataset to be able to develop and train a model.
Sometimes, we receive only one dataset.In such cases, we can split the dataset into two or three groups


Each dataset is comprised of inputs and targets. It is common to represent(말하다) the inputs with x or X and the targets with y or Y. We add the suffixes train,val,test to distinguish(드러내가다) each dataset.

In this recipe, we will learn about Pytorch data tools. We can use these tools to load and process data.

# How to do it..

In the following sections, you will learn how to use Pytorch packages to work with datasets.

# Loading a dataset

The Pytorch "torchvision" pacakge provides multiple popular datasets.

In [1]:
from torchvision import datasets

# path to store data and/or load from
path2data = "./data"

# loading training data
train_data = datasets.MNIST(path2data, train=True, download=True)

Extracting ./data\MNIST\raw\train-images-idx3-ubyte.gz to ./data\MNIST\raw


Extracting ./data\MNIST\raw\train-labels-idx1-ubyte.gz to ./data\MNIST\raw


Extracting ./data\MNIST\raw\t10k-images-idx3-ubyte.gz to ./data\MNIST\raw


Extracting ./data\MNIST\raw\t10k-labels-idx1-ubyte.gz to ./data\MNIST\raw
Processing...
Done!


In [ ]:
#2. T